version: "3"

dotenv: [".env"]

includes:
  gsplat:
    taskfile: ./gsplat/Taskfile.yaml
    dir: ./gsplat
  hierarchical-3d-gaussians:
    taskfile: ./hierarchical-3d-gaussians/Taskfile.yaml
    dir: ./hierarchical-3d-gaussians
    aliases: [h3dgs]
  3dgsconverter:
    taskfile: ./3dgsconverter/Taskfile.yaml
    dir: ./3dgsconverter
  nerfstudio:
    taskfile: ./nerfstudio/Taskfile.yaml
    dir: ./nerfstudio
    aliases: [ns]
  spatiallm:
    taskfile: ./spatiallm/Taskfile.yaml
    dir: ./spatiallm
    aliases: [slm]
  supersplat:
    taskfile: ./supersplat/Taskfile.yaml
    dir: ./supersplat
    aliases: [ss]
  3dgscd:
    taskfile: ./3dgscd/Taskfile.yaml
    dir: ./3dgscd

vars:
  PROJECTS:
    - gsplat
    - hierarchical-3d-gaussians
    - 3dgsconverter
    - nerfstudio
    - spatiallm
    - supersplat
    - 3dgscd


tasks:
  default:
    cmd: task --list-all

  clone-all:
    desc: Clone all repositories
    cmds:
      - for: { var: PROJECTS, as: PROJ }
        cmd: task {{ .PROJ }}:clone

  build-all:
    desc: Build all Docker images
    cmds:
      - for: { var: PROJECTS, as: PROJ }
        cmd: task {{ .PROJ }}:build

  push-all:
    desc: Push to Github Container Registry
    cmds:
      - for: { var: PROJECTS, as: PROJ }
        cmd: task {{ .PROJ }}:push

  pull-all:
    desc: Pull all images from Github Container Registry
    cmds:
      - for: { var: PROJECTS, as: PROJ }
        cmd: task {{ .PROJ }}:pull
