version: "3"

includes:
  common:
    taskfile: ../.templates/Taskfile.common.yaml
    dir: ./
    internal: true

vars:
  # - docker image
  NAME: # Image name
  VERSION_TAG: # Image version tag
  REPOSITORIES: # Repositories to push/pull
    -
  TAGS: # Tags are formed like so: REPO/NAME:VERSION_TAG, for REPO in REPOSITORIES
    sh: |
      for repo in {{ range $i, $repo := .REPOSITORIES }}{{ if $i }} {{ end }}"{{ $repo }}"{{ end }}; do
        echo "$repo/{{ .NAME }}:{{ .VERSION_TAG }}"
      done

  # - docker build
  BUILD_ARGS: # Optional build arguments for docker build
    ref: |
      dict
      "ARG1" "VALUE1"
      "ARG2" "VALUE2"

  # - cloning
  REPO: # Repository URL to clone
  REPO_PATH: # Output path for cloning. Recommended: ./repo
  COMMIT_ID: # Commit ID to checkout after cloning

tasks:
  default:
    cmd: task --list

  clone:
    desc: Clone {{.NAME}} and checkout {{.COMMIT_ID}}
    cmds:
      - task: common:clone

  build:
    desc: Build and tag image {{ .NAME }}:{{ .VERSION_TAG }}
    cmds:
      - task: common:build

  push:
    desc: Push image to registries {{.REPOSITORIES}}
    cmds:
      - task: common:push

  pull:
    desc: Pull image from registries {{.REPOSITORIES}}
    cmds:
      - task: common:pull

  run:
    desc: Run {{.NAME}}
    cmds:
      - task: common:run
