version: "3"

includes:
  common:
    taskfile: ../.templates/Taskfile.common.yaml
    dir: ./
    internal: true

vars:
  # - docker image
  NAME: segment-any-3d-gaussians
  VERSION_TAG: '1.0.0'
  REPOSITORIES:
    - ghcr.io/fabulani
  TAGS: # Tags are formed like so: REPO/NAME:VERSION_TAG, for REPO in REPOSITORIES
    sh: |
      for repo in {{ range $i, $repo := .REPOSITORIES }}{{ if $i }} {{ end }}"{{ $repo }}"{{ end }}; do
        echo "$repo/{{ .NAME }}:{{ .VERSION_TAG }}"
      done

  # - docker build
  BUILD_ARGS: # Optional build arguments for docker build
    ref: |
      dict
      "COMMIT_ID" "4acdaa6"
      "TORCH_CUDA_ARCH_LIST" "\"7.5+PTX\""

  # - cloning
  REPO: https://github.com/Jumpat/SegAnyGAussians.git
  REPO_PATH: ./repo
  COMMIT_ID: 4acdaa6

tasks:
  default:
    cmd: task --list

  clone:
    desc: Clone {{.NAME}} and checkout {{.COMMIT_ID}}
    cmds:
      - task: common:clone

  build:
    desc: Build and tag image {{ .NAME }}:{{ .VERSION_TAG }}
    cmds:
      - task: common:build

  push:
    desc: Push image to registries {{.REPOSITORIES}}
    cmds:
      - task: common:push

  pull:
    desc: Pull image from registries {{.REPOSITORIES}}
    cmds:
      - task: common:pull

  run:
    desc: Run {{.NAME}}
    cmds:
      - task: common:run
